# Generated by Django 4.1.1 on 2024-03-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='E7C1bAaDEcA09D8B', max_length=16, primary_key=True, serialize=False),
        ),
    ]
